// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/psych-profile/biz/adaptor"
	"github.com/xh-polaris/psych-profile/biz/adaptor/controller"
	"github.com/xh-polaris/psych-profile/biz/application/service"
	"github.com/xh-polaris/psych-profile/biz/infra/config"
	config2 "github.com/xh-polaris/psych-profile/biz/infra/mapper/config"
	"github.com/xh-polaris/psych-profile/biz/infra/mapper/unit"
	"github.com/xh-polaris/psych-profile/biz/infra/mapper/user"
)

// Injectors from wire.go:

func NewProvider() (*adaptor.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	iMongoMapper := user.NewMongoMapper(configConfig)
	unitIMongoMapper := unit.NewMongoMapper(configConfig)
	userService := &service.UserService{
		UserMapper: iMongoMapper,
		UnitMapper: unitIMongoMapper,
	}
	userController := &controller.UserController{
		UserService: userService,
	}
	unitService := &service.UnitService{
		UnitMapper: unitIMongoMapper,
		UserMapper: iMongoMapper,
	}
	unitController := &controller.UnitController{
		UnitService: unitService,
	}
	configIMongoMapper := config2.NewMongoMapper(configConfig)
	configService := &service.ConfigService{
		ConfigMapper: configIMongoMapper,
	}
	configController := &controller.ConfigController{
		ConfigService: configService,
	}
	server := &adaptor.Server{
		IUserController:   userController,
		IUnitController:   unitController,
		IConfigController: configController,
	}
	return server, nil
}
